# Sakura API 地址
endpoint: http://127.0.0.1:5000

# 工作目录
workspace: sample_project/

generate_config:
  temperature: 0.1
  top_p: 0.3
  max_tokens: 512
  frequency_penalty: 0.3
  extra_query:
    do_sample: False
    num_beams: 5
    repetition_penalty: 0.5
